### ISSUE TITLE
Make forEach, map etc compatible with their native counterparts

### ISSUE THREAD

**Issue by olivernn** [bloodyowl/craft#1]
I might be wrong but I don't think your implementation of the native ES5 array methods have the same signature as the native methods.  This will cause compatibility issues between browsers that use the native version and those that do not.

All of `forEach`, `map`, `filter`, `every` and `some` take an optional second argument which is used as the context for the function passed as the first argument.

You can see this in the [MDC docs](https://developer.mozilla.org/en-US/docs/JavaScript/Reference/Global_Objects/Array/forEach) and there are implementations and tests in [augment.js](https://github.com/olivernn/augment.js) and [es-5-shim](https://github.com/kriskowal/es5-shim) that may be useful.

**Comment by bloodyowl** [comment]
Well, I know that ES5 methods acts differently, but when you loop over an Array, a `func.call` can be really slow. That can seem to be weird, but that's why I decided to use a simple function call. 

Also, the Craft functions overwrite the native methods, so it doesn't change anything between the browsers. 

You can still use `Function#bind` to define a different context.

**Comment by olivernn** [comment]
Might be worth mentioning that you overwrite the native methods with an implementation that is not compatible in your docs.

As an aside I'm not sure that the overhead of using `call` is much of a bottleneck in many applications.

**Comment by bloodyowl** [comment]
After a few benchmarks to make my choice, I've just push the `0.1.5` version which adds a ES5 spec compatibility. `Array#forEach`, `Array#map` & `Array#filter` can now enable a context.
